version: '3'
services:
  xnat-web:
    env_file: "xnat.env"
    build:
      context: ./xnat
      args:
        XNAT_VER: ${XNAT_VER}
    image: brownbnc/xnat:${XNAT_VER}
    ports:
      - "8081:8080"
      - "8000:8000"
      - "8104:8104"
    volumes:
      - /data/xnat/home/logs:${XNAT_HOME}/logs
      - /data/xnat/home/plugins:${XNAT_HOME}/plugins
      - /data/xnat/home/config/auth:${XNAT_HOME}/config/auth
      - /data/xnat/archive:${XNAT_ROOT}/archive
      - /data/xnat/build:${XNAT_ROOT}/build
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx1024m -Dxnat.home=${XNAT_HOME} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - SMTP_ENABLED=false
      - SMTP_HOSTNAME=fake.fake
      # - SMTP_PORT:
      # - SMTP_AUTH:
      # - SMTP_USERNAME:
      # - SMTP_PASSWORD:
      - XNAT_DATASOURCE_DRIVER='org.postgresql.Driver'
      - XNAT_DATASOURCE_HOST=${XNAT_DATASOURCE_HOST}
      - XNAT_DATASOURCE_URL='jdbc:postgresql://${XNAT_DATASOURCE_HOST}:5432/xnat'
      - XNAT_DATASOURCE_USERNAME='xnat'
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}
      - HOST_URL=http://pbnccit.services.brown.edu