version: '3'
services:
  xnat-dev:
    build:
      context: ./xnat
      args:
        XNAT_VER: '1.7.5.1'
        XNAT_ROOT: /data/xnat-dev
    image: brownbnc/xnat:1.7.5.1
    ports:
      - "8081:8080"
      - "8000:8000"
      - "8104:8104"
    volumes:
      - /data/xnat/home/logs:/data/xnat/home/logs
      - /data/xnat/home/plugins:/data/xnat/home/plugins
      - /data/xnat/home/config:/data/xnat/home/config/
      - /data/xnat/archive:/data/xnat/archive
      - /data/xnat/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/xnat/tomcat/logs:/usr/local/tomcat/logs
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx1024m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000